import { create } from 'zustand';

const useCssStore = create((set) => ({
  fontFamily: 'CookieRun-Regular',
  fontUrl: `url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2001@1.1/CookieRun-Regular.woff') format('woff')`,
  fontSize: 28,
  fontBold: false,
  lineHeight: 36,
  fontEffect: 'none',
  fontEffectColor: { r: 0, g: 0, b: 0, a: 1 },
  shadowX: 2,
  shadowY: 2,
  shadowBlur: 4,
  boxEffect: 'none',
  boxBorder: 1,
  boxEffectColor: { r: 0, g: 0, b: 0, a: 1 },
  boxShadowX: 2,
  boxShadowY: 2,
  boxShadowBlur: 4,
  chatBgColor: { r: 0, g: 0, b: 0, a: 0.5 },
  chatTextColor: { r: 255, g: 255, b: 255, a: 1 },
  bodyBgColor: { r: 255, g: 255, b: 255, a: 0 },
  enableFadeOut: false,
  fadeDuration: 30,
  chatMarginBottom: 5,
  userIconSize: 32,
  stickerSize: 48,
  showNotice: false,
  noticeText: '방송 공지가 들어갑니다.',
  noticeFontSize: 28,
  noticeBgColor: { r: 0, g: 0, b: 0, a: 0.5 },
  noticeHeight: 64,
  chatRadius: 12,
  noticeRadius: 12,
  showNickname: true,
  blockNickname: false,
  bodyBgTransparent: true,
  chatBgTransparent: false,
  noticeBgTransparent: false,
  noticeTextColor: { r: 255, g: 255, b: 255, a: 1 },
  setFontFamily: (name, url) => set({
    fontFamily: name,
    fontUrl: url
  }),
  setBodyBgTransparent: (v) => set({ bodyBgTransparent: v }),
  setChatBgTransparent: (v) => set({ chatBgTransparent: v }),
  setNoticeBgTransparent: (v) => set({ noticeBgTransparent: v }),
  setFontSize: (v) => set({ fontSize: v }),
  setFontBold: (v) => set({ fontBold: v }),
  setLineHeight: (v) => set({ lineHeight: v }),
  setFontEffect: (v) => set({ fontEffect: v }),
  setFontEffectColor: (v) => set({ fontEffectColor: v }),
  setShadowX: (v) => set({ shadowX: v }),
  setShadowY: (v) => set({ shadowY: v }),
  setShadowBlur: (v) => set({ shadowBlur: v }),
  setBoxEffect: (v) => set({ boxEffect: v }),
  setBoxBorder: (v) => set({ boxBorder: v }),
  setBoxEffectColor: (v) => set({ boxEffectColor: v }),
  setBoxShadowX: (v) => set({ boxShadowX: v }),
  setBoxShadowY: (v) => set({ boxShadowY: v }),
  setBoxShadowBlur: (v) => set({ boxShadowBlur: v }),
  setChatBgColor: (v) => set({ chatBgColor: v }),
  setChatTextColor: (v) => set({ chatTextColor: v }),
  setBodyBgColor: (v) => set({ bodyBgColor: v }),
  setEnableFadeOut: (v) => set({ enableFadeOut: v }),
  setFadeDuration: (v) => set({ fadeDuration: v }),
  setChatMarginBottom: (v) => set({ chatMarginBottom: v }),
  setUserIconSize: (v) => set({ userIconSize: v }),
  setStickerSize: (v) => set({ stickerSize: v }),
  setShowNotice: (v) => set({ showNotice: v }),
  setNoticeText: (v) => set({ noticeText: v }),
  setNoticeFontSize: (v) => set({ noticeFontSize: v }),
  setNoticeBgColor: (v) => set({ noticeBgColor: v }),
  setNoticeHeight: (v) => set({ noticeHeight: v }),
  setChatRadius: (v) => set({ chatRadius: v }),
  setNoticeRadius: (v) => set({ noticeRadius: v }),
  setShowNickname: (v) => set({ showNickname: v }),
  setBlockNickname: (v) => set({ blockNickname: v }),
  setNoticeTextColor: (v) => set({ noticeTextColor: v }),
}));

export default useCssStore;